<?php

namespace App\Services\Chat;

use App\Models\Application;
use App\Models\Organization;
use App\Models\Program;
use App\Support\ApplicationProfile;

class ProjectKnowledgeRetriever
{
    private const STOPWORDS = [
        'the', 'and', 'for', 'what', 'does', 'how', 'are', 'with', 'this', 'that', 'from', 'about',
        'your', 'have', 'can', 'you', 'our', 'all', 'any', 'who', 'when', 'where', 'why',
    ];

    /**
     * @return list<array{id: string, title: string, text: string, meta: array<string, mixed>}>
     */
    public function retrieve(Organization $organization, ?int $programId, string $question, int $limit = 8): array
    {
        $chunks = array_merge(
            $this->platformChunks($organization),
            $this->applicationChunks($organization, $programId),
        );

        $scored = [];
        foreach ($chunks as $chunk) {
            $score = $this->scoreChunk($question, $chunk);
            if ($score > 0) {
                $scored[] = ['chunk' => $chunk, 'score' => $score];
            }
        }

        usort($scored, fn ($a, $b) => $b['score'] <=> $a['score']);

        if ($scored === []) {
            return array_slice($chunks, 0, min(3, count($chunks)));
        }

        return array_map(
            fn ($row) => $row['chunk'],
            array_slice($scored, 0, $limit)
        );
    }

    /**
     * @return list<array{id: string, title: string, text: string, meta: array<string, mixed>}>
     */
    private function platformChunks(Organization $organization): array
    {
        return [
            [
                'id' => 'platform:screening-score',
                'title' => 'AI screening scores',
                'text' => 'The AI screening score is a 0–100 overall rating generated by Google Gemini when a startup application is submitted. '
                    .'It reflects rubric criteria (team, market, traction, business model, etc.), includes a written summary, '
                    .'lists of strengths and weaknesses, risk flags with severity, and a recommendation such as accept, reject, shortlisted, or needs_info. '
                    .'Committee members use the score as structured input alongside human judgment — it does not replace the final decision.',
                'meta' => ['type' => 'platform'],
            ],
            [
                'id' => 'platform:screening-flow',
                'title' => 'Screening workflow',
                'text' => 'After a founder submits an application, VentureLens queues a Gemini screening job. '
                    .'Pitch deck PDFs are extracted and evaluated against the cohort rubric. '
                    .'Results appear on the application detail page with model name, latency, and token usage logged for audit.',
                'meta' => ['type' => 'platform'],
            ],
            [
                'id' => 'platform:billing',
                'title' => 'Plans and billing',
                'text' => "Organization {$organization->name} is on the {$organization->plan} plan with "
                    ."{$organization->screenings_used} of {$organization->screenings_quota} screenings used. "
                    .'Free trial includes 5 screenings. Cohort package ($199) includes 50 screenings. '
                    .'Starter ($299/mo) includes 200 screenings/month. Upgrade at Billing; manage subscription via Stripe portal.',
                'meta' => ['type' => 'platform'],
            ],
            [
                'id' => 'platform:cohorts',
                'title' => 'Cohorts and apply links',
                'text' => 'Each cohort (program) has a public apply link founders use to submit applications. '
                    .'Open Cohorts to copy the apply link, view application counts, and review submissions per program.',
                'meta' => ['type' => 'platform'],
            ],
            [
                'id' => 'platform:support',
                'title' => 'Support contacts',
                'text' => 'Support email: noreply@venturelens.app. Demo login: demo@venturelens.app.',
                'meta' => ['type' => 'platform'],
            ],
        ];
    }

    /**
     * @return list<array{id: string, title: string, text: string, meta: array<string, mixed>}>
     */
    private function applicationChunks(Organization $organization, ?int $programId): array
    {
        $programIds = $programId
            ? [$programId]
            : $organization->programs()->pluck('id')->all();

        if ($programIds === []) {
            return [];
        }

        $applications = Application::query()
            ->whereIn('program_id', $programIds)
            ->with(['program:id,name', 'latestScreeningResult'])
            ->orderByDesc('submitted_at')
            ->limit(40)
            ->get();

        $chunks = [];

        foreach ($applications as $application) {
            $chunks[] = $this->applicationToChunk($application);
        }

        if ($programId) {
            $program = Program::find($programId);
            if ($program) {
                $chunks[] = [
                    'id' => "program:{$program->id}",
                    'title' => "Cohort: {$program->name}",
                    'text' => "Program {$program->name} (status: {$program->status}). "
                        .($program->description ?: 'No description.')
                        ." {$applications->count()} applications in scope.",
                    'meta' => ['type' => 'program', 'program_id' => $program->id],
                ];
            }
        }

        return $chunks;
    }

    /**
     * @return array{id: string, title: string, text: string, meta: array<string, mixed>}
     */
    private function applicationToChunk(Application $application): array
    {
        $profile = ApplicationProfile::flattenForScreening($application->form_data);
        $screening = $application->latestScreeningResult;

        $parts = [
            "Startup: {$application->startup_name}",
            "Founder: {$application->founder_name}",
            "Cohort: {$application->program?->name}",
            "Status: {$application->status}",
            "Sector: {$application->sector}",
            "Stage: {$application->stage}",
        ];

        if ($application->ai_overall_score !== null) {
            $parts[] = "AI overall score: {$application->ai_overall_score}";
        }

        if ($screening) {
            $parts[] = "Screening score: {$screening->overall_score}";
            $parts[] = "Recommendation: {$screening->recommendation}";
            if ($screening->summary) {
                $parts[] = "Summary: {$screening->summary}";
            }
            if ($screening->strengths) {
                $parts[] = 'Strengths: '.implode('; ', $screening->strengths);
            }
            if ($screening->weaknesses) {
                $parts[] = 'Weaknesses: '.implode('; ', $screening->weaknesses);
            }
            if ($screening->risk_flags) {
                $flags = array_map(
                    fn ($f) => is_array($f) ? ($f['message'] ?? json_encode($f)) : (string) $f,
                    $screening->risk_flags
                );
                $parts[] = 'Risk flags: '.implode('; ', $flags);
            }
        }

        foreach (['problem', 'solution', 'traction', 'market', 'short_description'] as $key) {
            if (! empty($profile[$key])) {
                $parts[] = ucfirst(str_replace('_', ' ', $key)).': '.$profile[$key];
            }
        }

        return [
            'id' => "application:{$application->id}",
            'title' => $application->startup_name,
            'text' => implode("\n", $parts),
            'meta' => [
                'type' => 'application',
                'application_id' => $application->id,
                'program_id' => $application->program_id,
                'url' => "/applications/{$application->id}",
            ],
        ];
    }

    /**
     * @param  array{id: string, title: string, text: string}  $chunk
     */
    private function scoreChunk(string $question, array $chunk): float
    {
        $haystack = strtolower($chunk['title'].' '.$chunk['text']);
        $words = preg_split('/\W+/u', strtolower($question)) ?: [];
        $score = 0.0;

        foreach ($words as $word) {
            if (strlen($word) < 3 || in_array($word, self::STOPWORDS, true)) {
                continue;
            }
            if (str_contains($haystack, $word)) {
                $score += 1.0;
            }
        }

        if (preg_match('/\b(score|scoring|rating|recommendation)\b/i', $question)
            && str_starts_with($chunk['id'], 'platform:screening-score')) {
            $score += 12.0;
        }

        if (preg_match('/\b(screening|gemini|ai)\b/i', $question)
            && str_starts_with($chunk['id'], 'platform:')) {
            $score += 2.0;
        }

        if (preg_match('/\b(billing|plan|quota|screenings)\b/i', $question)
            && $chunk['id'] === 'platform:billing') {
            $score += 8.0;
        }

        if (preg_match('/\b(cohort|program|apply link)\b/i', $question)
            && in_array($chunk['id'], ['platform:cohorts'], true)) {
            $score += 6.0;
        }

        return $score;
    }
}
