<?php

namespace App\Services\Rag;

use App\Models\Application;
use App\Models\Organization;
use App\Models\Program;
use App\Support\ApplicationProfile;

class KnowledgeChunkBuilder
{
    /**
     * @return list<array{
     *     chunk_key: string,
     *     organization_id: int,
     *     program_id: int|null,
     *     source_type: string,
     *     source_id: int|null,
     *     title: string,
     *     content: string,
     *     metadata: array<string, mixed>,
     * }>
     */
    public function platformChunks(Organization $organization): array
    {
        $orgId = $organization->id;

        return [
            $this->doc($orgId, null, 'platform', null, 'platform:screening-score', 'AI screening scores',
                'The AI screening score is a 0–100 overall rating generated by Google Gemini when a startup application is submitted. '
                .'It aggregates rubric criteria (team, market, traction, business model, fit), produces a narrative summary, '
                .'lists strengths and weaknesses, surfaces risk flags with severity, and outputs a recommendation '
                .'(accept, reject, shortlisted, needs_info). Committees use it as structured input — not a final decision.'),
            $this->doc($orgId, null, 'platform', null, 'platform:screening-flow', 'Screening workflow',
                'Applications are screened asynchronously via a queue after submission. Pitch deck PDFs are extracted and evaluated against the cohort rubric. '
                .'Results include model name, latency, token counts, and agent execution logs for audit.'),
            $this->doc($orgId, null, 'platform', null, 'platform:billing', 'Plans and billing',
                "Organization {$organization->name} uses the {$organization->plan} plan ({$organization->screenings_used}/{$organization->screenings_quota} screenings). "
                .'Free trial: 5 screenings. Cohort package $199: 50 screenings. Starter $299/mo: 200/month. Billing page for upgrades; Stripe portal for subscription.'),
            $this->doc($orgId, null, 'platform', null, 'platform:cohorts', 'Cohorts and apply links',
                'Each program has a public apply link. Use Cohorts to copy links, track intake, and review applications per cohort.'),
            $this->doc($orgId, null, 'platform', null, 'platform:support', 'Support',
                'Support: noreply@venturelens.app. Demo login: demo@venturelens.app.'),
        ];
    }

    /**
     * @return list<array{
     *     chunk_key: string,
     *     organization_id: int,
     *     program_id: int|null,
     *     source_type: string,
     *     source_id: int|null,
     *     title: string,
     *     content: string,
     *     metadata: array<string, mixed>,
     * }>
     */
    public function applicationChunks(Application $application): array
    {
        $profile = ApplicationProfile::flattenForScreening($application->form_data);
        $screening = $application->latestScreeningResult;
        $orgId = $application->program->organization_id;
        $programId = $application->program_id;
        $appId = $application->id;

        $overview = implode("\n", array_filter([
            "Startup: {$application->startup_name}",
            "Founder: {$application->founder_name} ({$application->founder_email})",
            "Cohort: {$application->program?->name}",
            "Status: {$application->status}",
            "Sector: {$application->sector}",
            "Stage: {$application->stage}",
            "Country: {$application->country_code}",
            $profile['short_description'] ?? null,
        ]));

        $chunks = [
            $this->doc($orgId, $programId, 'application', $appId, "application:{$appId}:overview",
                $application->startup_name.' — overview', $overview,
                ['url' => "/applications/{$appId}", 'section' => 'overview']),
        ];

        if ($screening) {
            $riskFlagsText = $screening->risk_flags
                ? 'Risk flags: '.$this->formatRiskFlags($screening->risk_flags)
                : null;

            $screeningText = implode("\n", array_filter([
                "AI overall score: {$screening->overall_score}",
                "Recommendation: {$screening->recommendation}",
                $riskFlagsText,
                $screening->strengths ? 'Strengths: '.implode('; ', $screening->strengths) : null,
                $screening->weaknesses ? 'Weaknesses: '.implode('; ', $screening->weaknesses) : null,
                $screening->summary ? "Summary: {$screening->summary}" : null,
            ]));

            $chunks[] = $this->doc($orgId, $programId, 'application', $appId, "application:{$appId}:screening",
                $application->startup_name.' — screening', $screeningText,
                ['url' => "/applications/{$appId}", 'section' => 'screening']);

            if ($screening->risk_flags) {
                $chunks[] = $this->doc(
                    $orgId,
                    $programId,
                    'application',
                    $appId,
                    "application:{$appId}:risk-flags",
                    $application->startup_name.' — risk flags',
                    "Startup: {$application->startup_name}\n".$riskFlagsText,
                    ['url' => "/applications/{$appId}", 'section' => 'risk_flags'],
                );
            }
        }

        $narrative = implode("\n", array_filter([
            $profile['problem'] ?? null ? 'Problem: '.$profile['problem'] : null,
            $profile['solution'] ?? null ? 'Solution: '.$profile['solution'] : null,
            $profile['traction'] ?? null ? 'Traction: '.$profile['traction'] : null,
            $profile['market'] ?? null ? 'Market: '.$profile['market'] : null,
            $profile['business_model_summary'] ?? null ? 'Business model: '.$profile['business_model_summary'] : null,
        ]));

        if (trim($narrative) !== '') {
            $chunks[] = $this->doc($orgId, $programId, 'application', $appId, "application:{$appId}:narrative",
                $application->startup_name.' — narrative', $narrative,
                ['url' => "/applications/{$appId}", 'section' => 'narrative']);
        }

        $chunks[] = $this->doc(
            $orgId,
            $programId,
            'application',
            $appId,
            "application:{$appId}:founder",
            $application->founder_name.' — founder',
            implode("\n", array_filter([
                "Founder: {$application->founder_name}",
                "Email: {$application->founder_email}",
                "Startup: {$application->startup_name}",
                "Cohort: {$application->program?->name}",
                "Sector: {$application->sector}",
                "Stage: {$application->stage}",
                $profile['short_description'] ?? null,
            ])),
            [
                'url' => "/applications/{$appId}",
                'section' => 'founder',
                'founder_name' => $application->founder_name,
            ]
        );

        return $chunks;
    }

    /**
     * @return list<array{
     *     chunk_key: string,
     *     organization_id: int,
     *     program_id: int|null,
     *     source_type: string,
     *     source_id: int|null,
     *     title: string,
     *     content: string,
     *     metadata: array<string, mixed>,
     * }>
     */
    public function programChunk(Program $program): array
    {
        $count = $program->applications()->count();

        return [
            $this->doc(
                $program->organization_id,
                $program->id,
                'program',
                $program->id,
                "program:{$program->id}",
                "Cohort: {$program->name}",
                "Program {$program->name} (status: {$program->status}). "
                .($program->description ?: 'No description.')
                ." {$count} applications.",
                ['program_id' => $program->id]
            ),
        ];
    }

    /**
     * @param  array<string, mixed>  $metadata
     * @return array{
     *     chunk_key: string,
     *     organization_id: int,
     *     program_id: int|null,
     *     source_type: string,
     *     source_id: int|null,
     *     title: string,
     *     content: string,
     *     metadata: array<string, mixed>,
     * }
     */
    private function doc(
        int $orgId,
        ?int $programId,
        string $sourceType,
        ?int $sourceId,
        string $chunkKey,
        string $title,
        string $content,
        array $metadata = [],
    ): array {
        return [
            'chunk_key' => $chunkKey,
            'organization_id' => $orgId,
            'program_id' => $programId,
            'source_type' => $sourceType,
            'source_id' => $sourceId,
            'title' => $title,
            'content' => $content,
            'metadata' => array_merge(['type' => $sourceType], $metadata),
        ];
    }

    /**
     * @param  list<mixed>  $flags
     */
    private function formatRiskFlags(array $flags): string
    {
        return implode('; ', array_map(function ($f) {
            if (! is_array($f)) {
                return (string) $f;
            }
            $severity = isset($f['severity']) ? '['.$f['severity'].'] ' : '';
            $message = $f['message'] ?? json_encode($f);

            return $severity.$message;
        }, $flags));
    }
}
